name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows you to run this workflow manually

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install numpy matplotlib pandas scikit-learn

    - name: Generate sample data
      run: |
        python sample_data_generator.py << EOF
        y
        EOF
      shell: bash

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --add-data "tul_maintenance.db;." main.py

    - name: Create distribution package
      run: |
        mkdir dist_package
        copy dist\main.exe dist_package\TUL_Maintenance_Predictor.exe
        echo "# TUL Maintenance Predictor" > dist_package\README.txt
        echo. >> dist_package\README.txt
        echo "## How to Use" >> dist_package\README.txt
        echo "1. Double-click the TUL_Maintenance_Predictor.exe file" >> dist_package\README.txt
        echo "2. The application will open with sample data already included" >> dist_package\README.txt
        echo "3. Navigate to the Prediction tab to see 18-month wear forecasts" >> dist_package\README.txt
        echo. >> dist_package\README.txt
        echo "## New Features" >> dist_package\README.txt
        echo "- Extended prediction timeline to 18 months" >> dist_package\README.txt
        echo "- Improved maintenance pattern visualization" >> dist_package\README.txt
        echo "- More realistic wear simulation" >> dist_package\README.txt
        echo. >> dist_package\README.txt
        echo "No installation required!" >> dist_package\README.txt

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: TUL-Maintenance-Predictor
        path: dist_package
